### ISSUE TITLE
Node 18 causes connection failures to Roomba

### ISSUE THREAD

**Issue by Skyman81** [homebridge-plugins/homebridge-roomba2#126]
After last update of Homebridge I got this message:

![DC41C783-1DB5-4392-88AD-54D0A8FF77E0](https://user-images.githubusercontent.com/71496894/199070120-90701e4d-0b42-4334-879b-89bd54313a60.jpeg)

Roomba (mode 671) is well connected to wifi and his iRobot account… it’s only NOT working via homekit and HB.

**Comment by jeanchrijaz** [comment]
same issue with Roomba 980
the device is no longer detected in the home app

**Comment by NateUT99** [comment]
Did you upgrade nodejs to v18.x? I was having this exact issue and downgraded to v16.18.1 and it resolved my issues.

This can be done by running this command from the terminal on your Homebridge host:  _sudo hb-service update-node 16.18.1_

**Comment by Skyman81** [comment]
> Did you upgrade nodejs to v18.x? I was having this exact issue and downgraded to v16.18.1 and it resolved my issues. My guess is this plugin will need to be updated in order to support v18.x (there are a few others where this is causing issues too).
> 
> This can be done by running this command from the terminal on your Homebridge host: _sudo hb-service update-node 16.18.1_

Thank you IT WORKS!!!!

**Comment by thehauntedmattress** [comment]
Downgrading to Node 16.18.1 also fixed this exact same issue for me.

**Comment by afroeagle** [comment]
> After last update of Homebridge I got this message:
> 
> ![DC41C783-1DB5-4392-88AD-54D0A8FF77E0](https://user-images.githubusercontent.com/71496894/199070120-90701e4d-0b42-4334-879b-89bd54313a60.jpeg)
> 
> Roomba (mode 671) is well connected to wifi and his iRobot account… it’s only NOT working via homekit and HB.

I am having this same issue and downgrading to Node 16.18.1 also fixed this exact same issue for me.

**Comment by afroeagle** [comment]
> 

I am having this same issue and downgrading to Node 16.18.1 also fixed this exact same issue for me. Thank you @NateUT99

**Comment by jeanchrijaz** [comment]
> Did you upgrade nodejs to v18.x? I was having this exact issue and downgraded to v16.18.1 and it resolved my issues. My guess is this plugin will need to be updated in order to support v18.x (there are a few others where this is causing issues too).
> 
> This can be done by running this command from the terminal on your Homebridge host: _sudo hb-service update-node 16.18.1_

you only have rommba plugin?
because many other plugins require the new update of Homebrige
downgrade works but it is an "emergency repair"...

**Comment by NateUT99** [comment]
> > Did you upgrade nodejs to v18.x? I was having this exact issue and downgraded to v16.18.1 and it resolved my issues. My guess is this plugin will need to be updated in order to support v18.x (there are a few others where this is causing issues too).
> > This can be done by running this command from the terminal on your Homebridge host: _sudo hb-service update-node 16.18.1_
> 
> you only have rommba plugin? because many other plugins require the new update of Homebrige downgrade works but it is an "emergency repair"...

No, I have quite a few plugins… only one puts up a warning wanting v18 but it still functions. I agree, getting the plug-in updated is the best course of action; hopefully the author will (or someone will pick it up and continue working on it… all off the roomba plugins seem to be a bit stale at the moment).

**Comment by afroeagle** [comment]
@Skyman81 could you please update the title of this issue? A more actionable title will improve the chances of this issue being picked up and, therefore, resolved. May I suggest: "Plugin Stops Working After Update to Node.js 18.x"

**Comment by NateUT99** [comment]
Seems like this might have been a temporary solution... the problem has returned on my end. :(

**Comment by karlvr** [comment]
I've upgraded my setup and I'm trying to ascertain where's it's busted!

**Comment by karlvr** [comment]
I hope this is resolved once and for all with version 1.3.2-beta.1. Please try it out and let me know.

**Comment by NateUT99** [comment]
> I hope this is resolved with version 1.3.2-beta.1. Please try it out and re-open this issue if there are still Node 18 connection failures.

I’ll give it a shot when I return home tomorrow!

**Comment by Poonk81** [comment]
The beta works fine!! Thank you!

**Comment by karlvr** [comment]
@Poonk81 thank you very much for the confirmation. If you have time, there's another beta that tackles issues such as waking up Roomba less frequently. It would be great to know that it's still working nicely.

**Comment by thehauntedmattress** [comment]
The beta fixed this issue for me as well running Node 18.x.

**Comment by Poonk81** [comment]
> @Poonk81 thank you very much for the confirmation. If you have time, there's another beta that tackles issues such as waking up Roomba less frequently. It would be great to know that it's still working nicely.

I‘m using 1.3.2 beta 2 and it works fine.

**Comment by NateUT99** [comment]
Looks like plenty of positive feedback already, but just to add my own... installed 1.3.2-beta4 and NodeJS 18.12.1 and everything appears to be working as expected. Will start to watch and see if issues where Roomba makes the negative tone (and doesn't start) returns (will open new issue if it does).

**Comment by karlvr** [comment]
@NateUT99 thanks for that. It's always good to hear lots of 👍 before making a release. Especially with the latest beta as I did make a few releases over the weekend.

I think I might have fixed the negative tone and not starting issue in 931ba0d0c2b6fd3566a51af93f728c383fe7621b with any luck, which was in beta 4.

**Comment by NateUT99** [comment]
> @NateUT99 thanks for that. It's always good to hear lots of 👍 before making a release. Especially with the latest beta as I did make a few releases over the weekend.
> 
> I think I might have fixed the negative tone and not starting issue in [931ba0d](https://github.com/donavanbecker/homebridge-roomba2/commit/931ba0d0c2b6fd3566a51af93f728c383fe7621b) with any luck, which was in beta 4.

Based on your comments in that commit, I’m optimistic that might just do the trick… will report back after a few days!

**Comment by jeanchrijaz** [comment]
@karlvr 
beta3 worked better for me since I installed 1.3.2-beta4 and NodeJS 18.12.1 and I have a lot of disconnection
I have downgraded NodeJS to v16.18.0 and v1.3.1 for roomba plugin

**Comment by karlvr** [comment]
@jeanchrijaz thanks for your feedback. That is weird. Could I put upon you to try beta4 again and see perhaps turn on Debug logging on the plugin? It's one of the plugin options (right down the bottom). That way we might learn something that helps us track down what's occurring for you.

**Comment by jeanchrijaz** [comment]
> @jeanchrijaz thanks for your feedback. That is weird. Could I put upon you to try beta4 again and see perhaps turn on Debug logging on the plugin? It's one of the plugin options (right down the bottom). That way we might learn something that helps us track down what's occurring for you.

I did not have the problem immediately but a few days later
I have a roomba 980 with a static ip
the rebot was restarted but it loses connection with homebridge and home app. 
I will retest tonight or tomorrow with Debug logging activated.

**Comment by karlvr** [comment]
@jeanchrijaz I've just released a new beta to tune a few things. beta5. Please give that a try and let us know how it goes.

**Comment by jeanchrijaz** [comment]
@karlvr 
ok I will test tonight (I'm not at home)

**Comment by karlvr** [comment]
This new beta seems to be working well enough to release and resolve these Node 18 issues for everyone. Please upgrade to v1.4.0.
