### ISSUE TITLE
Roomba’s light is,always on with plug-in

### ISSUE THREAD

**Issue by TommyGKiwi** [homebridge-plugins/homebridge-roomba2#127]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **Plugin**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by Write** [comment]
i've made a fork to change all timers , and default config fix the light issue : https://github.com/Write/homebridge-roomba2

**Comment by Write** [comment]
> > i've made a fork to change all timers , and default config fix the light issue : https://github.com/Write/homebridge-roomba2
> 
> Installed this fork a few days ago and must say my Roomba has never been more stable in HomeKit! It would be great to get this integrated back into the "main" repo, but in the meantime thanks for making it available.

Glad to hear it, you're the first feedback I actually got, it means a lot to me !

**Comment by TommyGKiwi** [comment]
HiWill try after I reinstall homebridge as the roomba app can’t connect, unless I shutdown  the rpi, even though I removed the plugin (I had tried previously another plugin so I do not know which caused it. Sent from my iPhoneOn Nov 17, 2022, at 9:22, Joffrey ***@***.***> wrote:﻿


i've made a fork to change all timers , and default config fix the light issue : https://github.com/Write/homebridge-roomba2

Installed this fork a few days ago and must say my Roomba has never been more stable in HomeKit! It would be great to get this integrated back into the "main" repo, but in the meantime thanks for making it available.

Glad to hear it, you're the first feedback I actually got, it means a lot to me !

**Comment by karlvr** [comment]
@Write awesome that you've been working on the plugin... would you like to open some pull requests? One per issue please so I can understand what you're doing and we can discuss!

**Comment by karlvr** [comment]
@TommyGKiwi I'm not clear on what problem you're reporting from just the issue title. @Write has the same problem and has solved it, it seems, but I would like to understand what you're experiencing too! Can you please provide some details?

**Comment by karlvr** [comment]
@TommyGKiwi also please try the latest _beta_ of this plugin and let us know if that resolves this issue. You can install the beta in Homebridge by clicking the wrench / spanner icon on the plugin and choosing _Install Alternate Version_.

**Comment by karlvr** [comment]
Closing as I think 1.4.0 has addressed this.
