### ISSUE TITLE
Accessory not found

### ISSUE THREAD

**Issue by germanh2** [homebridge-plugins/homebridge-roomba2#132]
I've followed the steps and was able to get the blid and password for my Roomba 960. I can see the Roomba in my accessories dashboard on Hoobs, and when clicked it will start the Roomba, and then when clicking again it will return it back to its base. However, when I scan the QR code to setup in Home, it states accessory not found. Everything is on the same network and I was able to get other bridges setup successfully with Hoobs and Home application. 

### Versions
Hoobs version 4.2.8
Home Bridge Version: 1.5.0
System Version: 11

### Configuration
{
    "accessories": [
        {
            "accessory": "Roomba2",
            "plugin_map": {
                "plugin_name": "homebridge-roomba2"
            },
            "name": "Roomba",
            "model": "960",
            "robotpwd": ":10000000000",
            "blid": "myblidNumbers",
            "ipaddress": "10.0.0.15",
            "dockContactSensor": true,
            "binContactSensor": true,
            "runningContactSensor": true,
            "dockingContactSensor": true,
            "homeSwitch": false,
            "stopBehaviour": "home",
            "serialnum": "R9600"
        }
    ]
}

### Homebridge Log / Command Output1/22/2023, 5:39:01 PMRoomba2 BridgeConfiguration change
1/23/2023, 12:19:40 AMRoomba2 Bridge starting
1/23/2023, 12:19:56 AMRoomba2 BridgeLoaded plugin 'homebridge-roomba2'
1/23/2023, 12:19:57 AMRoomba2 BridgeRegistering accessory 'homebridge-roomba2.Roomba2'
1/23/2023, 12:19:57 AMRoomba2 BridgeLoading 1 accessories...
1/23/2023, 12:19:57 AMRoomba2 BridgeRoombaAutomatically refreshing Roomba's status
1/23/2023, 12:19:57 AMRoomba2 BridgeRoombaConnecting to Roomba (0 others waiting)...
1/23/2023, 12:19:57 AMRoomba2 BridgeSetup URI 'X-HM://0023ISYWYE8PL'
1/23/2023, 12:19:57 AMRoomba2 BridgeBridge is running on port 51856.
1/23/2023, 12:20:01 AMRoomba2 BridgeRoombaConnected to Roomba in 4387ms
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba On from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Charging State from undefined to 1
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Battery Level from undefined to 100
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Status Low Battery from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Filter Change Indication from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Dock Contact Sensor State from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Running Contact Sensor State from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Bin Full Contact Sensor State from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaUpdating Roomba Docking Contact Sensor State from undefined to 0
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaMerged updated state {"timestamp":1674451202470,"batteryLevel":100,"binFull":false,"running":false,"charging":true,"docking":false,"paused":false} => {"timestamp":1674451202470,"batteryLevel":100,"binFull":false,"running":false,"charging":true,"docking":false,"paused":false}
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaRefreshed Roomba's state in 5436ms: {"netinfo":{"dhcp":true,"addr":167772165,"mask":4294967040,"gw":167772161,"dns1":167772161,"dns2":0,"bssid":"6c:cd:d6:14:35:55","sec":4},"wifistat":{"wifi":1,"uap":false,"cloud":1},"wlcfg":{"sec":7,"ssid":"4F5242492D57414E2D4B454E4F4249"},"mac":"dc:f5:05:6a:c1:c4","country":"US","cloudEnv":"prod","svcEndpoints":{"svcDeplId":"v005"},"wifiAnt":1,"mapUploadAllowed":true,"localtimeoffset":-300,"utctime":1674451202,"pose":{"theta":0,"point":{"x":102,"y":0}},"batPct":100,"dock":{"known":false},"bin":{"present":true,"full":false},"cleanMissionStatus":{"cycle":"none","phase":"charge","expireM":0,"rechrgM":0,"error":0,"notReady":0,"mssnM":0,"mssnStrtTm":0,"expireTm":0,"rechrgTm":0,"sqft":0,"initiator":"localApp","nMssn":206},"language":0,"noAutoPasses":false,"noPP":false,"ecoCharge":false,"vacHigh":false,"binPause":true,"carpetBoost":true,"openOnly":false,"twoPass":false,"schedHold":false}
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaWill refresh Roomba's status again automatically in 15m
1/23/2023, 12:20:02 AMRoomba2 BridgeRoombaMerged updated state {"timestamp":1674451202609,"batteryLevel":100,"binFull":false,"running":false,"charging":true,"docking":false,"paused":false} => {"timestamp":1674451202609,"batteryLevel":100,"binFull":false,"running":false,"charging":true,"docking":false,"paused":false}

**Comment by karlvr** [comment]
@germanh2 are you still having this problem? This seems like this is an issue getting Hoobs connected to your HomeKit rather than a problem with the plugin so I am closing this issue. Please re-open if it appears that it's a problem with this plugin.
