### ISSUE TITLE
Roomba 2 plug-in configuration problem

### ISSUE THREAD

**Issue by Cyrille556** [homebridge-plugins/homebridge-roomba2#37]
Hello, I have just redone my homebridge installation and I can no longer configure the plug-in, Roomba2 several error message is displayed in the configuration terminal. Help me please
<img width="1066" alt="Capture d’écran 2021-03-18 à 18 35 30" src="https://user-images.githubusercontent.com/78914215/111671852-a2186600-8819-11eb-9f3a-5de670674c74.png">

**Comment by Chennyisafrag** [comment]
Make sure you run the command in the plug in directory, its probably "/usr/local/lib/node_modules/homebridge-roomba2". Basically run "npm root -g" and what ever that returns just add "/homebridge-roomba2". Then run getrobotpwd from there.

**Comment by Cyrille556** [comment]
Thanks for help but I can't do what you advise me to do, I still have the same problem

**Comment by MrAndersonMD** [comment]
Configuration is OK, including blid and robotpswd, but accesory is "not responding".

**Comment by Chennyisafrag** [comment]
> Thanks for help but I can't do what you advise me to do, I still have the same problem

Change your directory to homebridge-roomba2...Then run the command from there.

**Comment by skazzyskills** [comment]
I have the same problem.

**Comment by Chennyisafrag** [comment]
Are you having the same issues as this person below?

> Hello, I have just redone my homebridge installation and I can no longer configure the plug-in, Roomba2 several error message is displayed in the configuration terminal. Help me please
> <img alt="Capture d’écran 2021-03-18 à 18 35 30" width="1066" src="https://user-images.githubusercontent.com/78914215/111671852-a2186600-8819-11eb-9f3a-5de670674c74.png">

**Comment by skazzyskills** [comment]
This is what I see:
<img width="687" alt="Screen Shot 2021-04-08 at 9 19 47 PM" src="https://user-images.githubusercontent.com/49604280/114128036-530da000-98b0-11eb-89fa-08986bd1e4bf.png">

**Comment by Chennyisafrag** [comment]
Make sure you **CD** into where your plugins are installed. You can find this by typing npm root -g

**Comment by skazzyskills** [comment]
How do I do this in terminal? I tried entering in the command: cd /usr/local/lib/node_modules
then running the get password command, but I still get the same error. What am I missing?

**Comment by Chennyisafrag** [comment]
From previous...
> Make sure you run the command in the plug in directory, its probably "/usr/local/lib/node_modules/homebridge-roomba2". Basically run "npm root -g" and what ever that returns **just add "/homebridge-roomba2".** Then run getrobotpwd from there.

**Comment by skazzyskills** [comment]
Thank you! Got it! Thanks!

**Comment by skazzyskills** [comment]
Wait, there's nothing listed there that says 'model'. But it's a field I have to fill out in the settings. What do I put. M6?

**Comment by Chennyisafrag** [comment]
Here is my config:

{
"name": "Miss Vroom",
"model": "i7",
"blid": "4***********************E",
"robotpwd": ":1:1*******************K",
"ipaddress": "192.168.1.63",
"autoRefreshEnabled": true,
"keepAliveEnabled": true,
"dockContactSensor": true,
"binContactSensor": true,
"cacheTTL": 30,
"accessory": "Roomba2"
}

**Comment by Chennyisafrag** [comment]
I don’t think it matters the plug-in don’t officially support anything above the 900s. It’s just a value it passes on to homebridge

**Comment by skazzyskills** [comment]
Ok great. Cheers!


Shawn Skalinski
***@***.***

**Comment by skazzyskills** [comment]
@Chennyisafrag having issues with my M6 mop. Getting constant 'no response' in HomeKit. Just noticed in the Eve app it says battery for my M6 mop is at 0% but Roomba says 100%. I wonder if this is the issue for the constants ‘no response’ I’m getting for this accessory? The plugin is not reading the percentage properly? And therefore it’s giving me a no response? Does anybody have this working?

**Comment by skazzyskills** [comment]
Confirmed. In Homebridge, it registers as 'not charging' and at 0%. BUT, it is actually 100% charged and works if I hit the power button in Homebridge. Hmmm..

**Comment by Chennyisafrag** [comment]
@skazzyskills make sure you have a static IP set to the M6... you can try messing with the cache settings to make it more stable...

**Comment by skazzyskills** [comment]
IP is static. Works fine in the homebridge interface. The hangup is the translation into HomeKit. Definitely has something to do with requesting the status of the battery. It’s coming through at 0% rather than 100% and because of this I think it’s getting the no response.

Shawn Skalinski
***@***.***

**Comment by Chennyisafrag** [comment]
I don’t see any other solutions... it’s been a while since the project was updated... I’m sure it’s something you can overlook since the M6 has recharge and resume.

**Comment by brufal** [comment]
@Chennyisafrag Hello, i'm a new user for homebridge, and i would to start with this plugin, but i have the same problem like you have show to us in one of your previous message.
My question is in homebridge where i can find the "the plug in directory" because in the the Terminal this the cmd 

> From previous...
> 
> > Make sure you run the command in the plug in directory, its probably "/usr/local/lib/node_modules/homebridge-roomba2". Basically run "npm root -g" and what ever that returns **just add "/homebridge-roomba2".** Then run getrobotpwd from there.

Here you can find what i have when i follow your instruction

![Capture d’écran 2021-04-28 à 21 44 41](https://user-images.githubusercontent.com/83335117/116463661-40f99e80-a86b-11eb-91c1-3eb7a2f0102b.png)

if you can help me that should be great.

**Comment by Chennyisafrag** [comment]
@brufal Would recommend watching or reading a couple get started with Linux/Raspbian materials. But to solve your issue you need to put **"cd"** in front of the directory you want to move to. In your case, it would be "cd /usr/local/lib/node_modules/ homebridge-roomba2"

**Comment by brufal** [comment]
@Chennyisafrag Thanks for your first help, i have just try your cmd suggest, but i receive the following answer
![Capture d’écran 2021-04-28 à 22 00 29](https://user-images.githubusercontent.com/83335117/116465220-39d39000-a86d-11eb-92d3-c6a7ccd5e8b5.png)

**Comment by Chennyisafrag** [comment]
Remove the space between node_modules/ and homebridge-roomba2.

**Comment by brufal** [comment]
i receive an answer was : "No such file or directory"

**Comment by Chennyisafrag** [comment]
Just to confirm... Is the plug-in install in homebridge?

**Comment by brufal** [comment]
Yes of course. @Chennyisafrag 
I am not a pro, but I know to do some basic tips and install before try to configure is always better ahaha  ;-)

![Capture d’écran 2021-04-28 à 23 30 24](https://user-images.githubusercontent.com/83335117/116475165-be2c1000-a879-11eb-94f7-b0f312b0931e.png)

**Comment by Chennyisafrag** [comment]
Just cd into “ /usr/local/lib/node_modules” then run “dir” and check if homebridge-roomba2 is there

**Comment by brufal** [comment]
I have try your cmd and this is the result 👇🏼

![BD062979-8733-4344-8A1A-C96855A6140C](https://user-images.githubusercontent.com/83335117/116476579-b66d6b00-a87b-11eb-85ab-a11e8d3da1ad.jpeg)

**Comment by Chennyisafrag** [comment]
You need a space between cd and the directory you wish to go to

**Comment by brufal** [comment]
I have the same things with the space
![AADF4C49-04DD-4D31-8F91-401708BD07A1](https://user-images.githubusercontent.com/83335117/116477059-63e07e80-a87c-11eb-84eb-0bf8cb721a19.jpeg)

**Comment by Chennyisafrag** [comment]
Lol... auto correct

**Comment by brufal** [comment]
?? Where?

**Comment by brufal** [comment]
I have find the mistake between “usr” and “user”

**Comment by brufal** [comment]
@Chennyisafrag hey thanks to your help I have finished successfully the setting of my Roomba I haven’t tested yet  but now I can see it in my app Home. 
i’m going to try it today.  I am a French guy so sorry if we have some delay between an answer because we have a different time zone

**Comment by Chennyisafrag** [comment]
Great! Make sure you set a static IP for the Roomba on your router.
